// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go Celeb Poc
A POC to test Payment Service via PayPal


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0
    Contact: Payment API Support

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
