swagger: '2.0'
info:
  title: Go Celeb Poc
  description: A POC to test Payment Service via PayPal
  contact:
    name: Payment API Support
  version: 1.0.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    $ref: ./paths/test.yml
definitions:
  generalResponse:
    $ref: ./definitions/generalResponse.yml

basePath: /v1